# Generated by Django 6.1.1 on 2026-09-21 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SL Deskline', help_text='Shown in the header, page titles, social previews and outbound email.', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Shown in the header in place of the site name text when set.', upload_to='branding/')),
                ('accent_color', models.CharField(default='#7c3aed', help_text='Hex colour (e.g. #7c3aed) used for links, buttons and other accents.', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour code in the form #rrggbb.', regex='^#[0-9a-fA-F]{6}$')])),
                ('support_email', models.EmailField(blank=True, help_text='Shown in the KB/ticket footer and outbound email when set.', max_length=254)),
                ('notification_from_email', models.EmailField(blank=True, help_text='From-address for outbound ticket email. Falls back to DEFAULT_FROM_EMAIL when blank.', max_length=254)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
