# Generated by Django 6.1.1 on 2026-09-21 11:32

import django.db.models.deletion
import kb.validators
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('summary', models.TextField(help_text='Short standalone summary of what this article covers — shown in listings and used as a search-result snippet.')),
                ('body', markdownx.models.MarkdownxField(blank=True, default='', help_text='Main article content, written in Markdown (prose explaining a feature or answering a question). Optional if the article is purely a numbered how-to — see ArticleStep.')),
                ('meta_description', models.CharField(blank=True, help_text='Falls back to a truncated summary if left blank.', max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('sort_order', models.PositiveIntegerField(blank=True, help_text='Optional. Lower numbers are listed first within their category; leave blank to list by newest.', null=True, verbose_name='Order')),
                ('author_user_id', models.PositiveIntegerField()),
                ('author_display_name', models.CharField(help_text='Cached at publish time from the authoring user — avoids a lookup against auth.User on every page render.', max_length=150)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.PositiveIntegerField(blank=True, help_text="Null = the site's own public KB. Set = a specific org's private KB (add-on).", null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public — visible to every visitor'), ('members', 'Members only — signed-in users who belong to an organisation')], default='public', help_text='Members-only categories are hidden from anonymous visitors and from signed-in users who belong to no organisation. Organisation members and support agents can see them.', max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers are listed first. Leave at 0 to sort alphabetically among the other unordered categories.', verbose_name='Order')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "Track every request in one place".', max_length=120)),
                ('screenshot', models.ImageField(upload_to='showcase/', validators=[kb.validators.validate_image_size])),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('cta_label', models.CharField(default='Learn more', max_length=60)),
                ('cta_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.PositiveIntegerField(blank=True, help_text="Null = the site's own public KB. Set = a specific org's private KB.", null=True)),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('instruction', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='kb.article')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ArticlePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/%Y/%m/', validators=[kb.validators.validate_image_size])),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='kb.article')),
                ('step', models.ForeignKey(blank=True, help_text='Left blank for an article-level (e.g. hero) photo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='kb.articlestep')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='kb.category'),
        ),
        migrations.CreateModel(
            name='FeaturedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('curated_by_user_id', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_runs', to='kb.article')),
            ],
            options={
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('anon_token', models.CharField(blank=True, help_text='Random token stored in a long-lived cookie for anonymous readers.', max_length=64, null=True)),
                ('is_helpful', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='kb.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='kb.tag'),
        ),
        migrations.AddConstraint(
            model_name='articlestep',
            constraint=models.UniqueConstraint(fields=('article', 'order'), name='unique_step_order_per_article'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(condition=models.Q(('user_id__isnull', False)), fields=('article', 'user_id'), name='unique_rating_per_user'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(condition=models.Q(('anon_token__isnull', False)), fields=('article', 'anon_token'), name='unique_rating_per_anon_token'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-published_at'], name='kb_article_status_730390_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['org_id', 'status'], name='kb_article_org_id_b85fc3_idx'),
        ),
    ]
