# Generated by Django 6.1.1 on 2026-09-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_article_search_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='KBSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings_enabled', models.BooleanField(default=True, help_text='Off hides the Yes/No buttons and the comment box, and stops new votes. Existing feedback is kept.', verbose_name='Ask "Was this article helpful?" on articles')),
                ('show_helpful_count', models.BooleanField(default=True, verbose_name='Show "X found this helpful" on article cards')),
            ],
            options={
                'verbose_name': 'KB settings',
                'verbose_name_plural': 'KB settings',
            },
        ),
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
