# Generated by Django 6.1 on 2026-09-24 16:00

import kb.youtube
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_rating_comment_kbsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_display',
            field=models.CharField(choices=[('embed', 'Embedded player'), ('thumbnail', 'Thumbnail linking to YouTube'), ('button', '"Watch on YouTube" button')], default='embed', max_length=10, verbose_name='Show video as'),
        ),
        migrations.AddField(
            model_name='article',
            name='youtube_video_id',
            field=kb.youtube.YouTubeVideoIdField(blank=True, default='', help_text='Optional. Paste the video’s YouTube link (or its ID).', max_length=11, verbose_name='YouTube video'),
        ),
    ]
